[project]
name = "classyfire"
version = "0.1.0"
description = "Classy research articles"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlit>=1.49.1",
    "tinydb>=4.8.2",
]

[project.optional-dependencies]
dev = [
    "pre-commit>=4.3.0",
]
